/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sub.h"

int *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Subtraction(%d, %d) is called\n",argp->a, argp->b);
	result= argp->a - argp->b;

	return &result;
}
